# action.yml
name: 'Spring Application Advisor'
description: 'Incrementally upgrade your Spring application dependencies'
branding:
  icon: user-check
  color: green
inputs:
  artifactory_token:
    description: 'Token for Spring Enterprise Subscription'
    required: true
  git_token:
    description: 'Authentication token for generating pull requests against repo'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run App Advisor
      run: ${{ github.action_path }}/app-advisor.sh
      shell: bash
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        GIT_TOKEN_FOR_PRS: ${{ inputs.git_token }}
